//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicWebForms.forms {
    
    
    public partial class PartnerstviOsaZive {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// body control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl body;
        
        /// <summary>
        /// form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form;
        
        /// <summary>
        /// scriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager scriptManager;
        
        /// <summary>
        /// mvForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView mvForm;
        
        /// <summary>
        /// viewForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewForm;
        
        /// <summary>
        /// rbZadostTrue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbZadostTrue;
        
        /// <summary>
        /// rbZadostFalse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbZadostFalse;
        
        /// <summary>
        /// tbZadostNe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbZadostNe;
        
        /// <summary>
        /// rbUspokTrue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbUspokTrue;
        
        /// <summary>
        /// rbUspokFalse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbUspokFalse;
        
        /// <summary>
        /// tbNazevProjektu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbNazevProjektu;
        
        /// <summary>
        /// tbNazevOsoby control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbNazevOsoby;
        
        /// <summary>
        /// tbICRC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbICRC;
        
        /// <summary>
        /// tbDIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbDIC;
        
        /// <summary>
        /// tbStatutZast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbStatutZast;
        
        /// <summary>
        /// tbFunkce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbFunkce;
        
        /// <summary>
        /// tbPravniForma control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPravniForma;
        
        /// <summary>
        /// tbRegistrace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbRegistrace;
        
        /// <summary>
        /// tbBankSpoj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbBankSpoj;
        
        /// <summary>
        /// tbNazevBanky control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbNazevBanky;
        
        /// <summary>
        /// tbCisloUctu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCisloUctu;
        
        /// <summary>
        /// tbKraj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbKraj;
        
        /// <summary>
        /// tbMesto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbMesto;
        
        /// <summary>
        /// tbPSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPSC;
        
        /// <summary>
        /// tbTelefon control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbTelefon;
        
        /// <summary>
        /// tbEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbEmail;
        
        /// <summary>
        /// tbWWW control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbWWW;
        
        /// <summary>
        /// tbKontaktOsoba control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbKontaktOsoba;
        
        /// <summary>
        /// tbTelefonKontakt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbTelefonKontakt;
        
        /// <summary>
        /// tbEmailKontakt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbEmailKontakt;
        
        /// <summary>
        /// tbCinnost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCinnost;
        
        /// <summary>
        /// tbDelkaPusobeni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbDelkaPusobeni;
        
        /// <summary>
        /// tbReference control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbReference;
        
        /// <summary>
        /// tbPredpoklady control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPredpoklady;
        
        /// <summary>
        /// tbPopisCileProjektu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPopisCileProjektu;
        
        /// <summary>
        /// tbSeznamVykonnych control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbSeznamVykonnych;
        
        /// <summary>
        /// tbMistoRealizace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbMistoRealizace;
        
        /// <summary>
        /// tbCasovyPrubeh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCasovyPrubeh;
        
        /// <summary>
        /// tbOdhadPocNavs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbOdhadPocNavs;
        
        /// <summary>
        /// tbKategorieVstupneho control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbKategorieVstupneho;
        
        /// <summary>
        /// tbSponzori control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbSponzori;
        
        /// <summary>
        /// tbRozpocet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbRozpocet;
        
        /// <summary>
        /// tbVlastniZdroje control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbVlastniZdroje;
        
        /// <summary>
        /// tbZCelkRozp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbZCelkRozp;
        
        /// <summary>
        /// tbZiskaneProstredky control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbZiskaneProstredky;
        
        /// <summary>
        /// tbNaProjZJinZdr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbNaProjZJinZdr;
        
        /// <summary>
        /// tbCelkNaklNaProj control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCelkNaklNaProj;
        
        /// <summary>
        /// tbCelkNaklNaVyk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCelkNaklNaVyk;
        
        /// <summary>
        /// tbZTohoNaklNaCest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbZTohoNaklNaCest;
        
        /// <summary>
        /// cbZmineniJakoPartnera control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbZmineniJakoPartnera;
        
        /// <summary>
        /// tbZmineniJakoPartnera control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbZmineniJakoPartnera;
        
        /// <summary>
        /// cbUmisteniPrezentace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbUmisteniPrezentace;
        
        /// <summary>
        /// tbUmisteniPrezentace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbUmisteniPrezentace;
        
        /// <summary>
        /// cbUmisteniTisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbUmisteniTisk;
        
        /// <summary>
        /// tbUmisteniTisk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbUmisteniTisk;
        
        /// <summary>
        /// cbPodekovani control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbPodekovani;
        
        /// <summary>
        /// tbPodekovani control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPodekovani;
        
        /// <summary>
        /// cbUmisteniProgram control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbUmisteniProgram;
        
        /// <summary>
        /// tbUmisteniProgram control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbUmisteniProgram;
        
        /// <summary>
        /// cbPrezentaceVMiste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbPrezentaceVMiste;
        
        /// <summary>
        /// tbPrezentaceVMiste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbPrezentaceVMiste;
        
        /// <summary>
        /// cbRozdavaniPropMat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbRozdavaniPropMat;
        
        /// <summary>
        /// tbRozdavaniPropMat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbRozdavaniPropMat;
        
        /// <summary>
        /// cbUmisteniWeb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbUmisteniWeb;
        
        /// <summary>
        /// tbUmisteniWeb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbUmisteniWeb;
        
        /// <summary>
        /// tbNabidkaDalsihoPlneni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbNabidkaDalsihoPlneni;
        
        /// <summary>
        /// cbSouhlasZverejneni control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbSouhlasZverejneni;
        
        /// <summary>
        /// cbSouhlasOsUd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaCheckBox cbSouhlasOsUd;
        
        /// <summary>
        /// tbProhlaseniKontaktOsoba control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbProhlaseniKontaktOsoba;
        
        /// <summary>
        /// tbProhlaseniKontaktFunkce control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbProhlaseniKontaktFunkce;
        
        /// <summary>
        /// tbProhlaseniDatum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbProhlaseniDatum;
        
        /// <summary>
        /// upForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upForm;
        
        /// <summary>
        /// lbCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbCaptcha;
        
        /// <summary>
        /// captcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MSCaptcha.CaptchaControl captcha;
        
        /// <summary>
        /// tbCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PublicWebForms.OsaTextBox tbCaptcha;
        
        /// <summary>
        /// lbSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbSave;
        
        /// <summary>
        /// viewComplete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewComplete;
        
        /// <summary>
        /// LinkButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;
        
        /// <summary>
        /// viewError control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View viewError;
        
        /// <summary>
        /// LinkButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton2;
    }
}
